### ISSUE TITLE
Error with the callback

### ISSUE THREAD

**Issue by EchterAlsFake** [Egsagon/PHUB#20] opened 2023-10-02 15:15 UTC
Hi,

I got this error, when downloading a video with the default downloader:

 ```
Traceback (most recent call last):
  File "/home/asuna/PycharmProjects/Porn_Fetch/Porn_Fetch.py", line 221, in run
    self.video.download(downloader=default, display=self.callback, quality=self.quality, path=self.output_path)
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/video.py", line 204, in download
    downloader(
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/modules/download.py", line 70, in default
    callback(i + 1, length)
TypeError: 'Callback' object is not callable
 ```

Using newest commits from your repo.

**Comment by Egsagon** [comment] 2023-10-02 15:36
Should be fixed, thanks for reporting!

**Closed** 2023-10-02 15:35 UTC

**Comment by EchterAlsFake** [comment] 2023-10-02 19:24
Hi again,

with the commit [fc9b330](https://github.com/Egsagon/PHUB/commit/fc9b330164c9cecfad41f537b3617a20cc648ebf) I got this error:
 ``` 
  File "/home/asuna/PycharmProjects/Porn_Fetch/venv/lib/python3.11/site-packages/phub/objects/data.py", line 193, in new
    if issubclass(obj, Callback):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: issubclass() arg 1 must be a class
 ```

**Comment by Egsagon** [comment] 2023-10-02 19:25
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by Egsagon** [comment] 2023-10-02 19:51
Hi.
These errors where caused by me trying to implement a proper callback system. The goal was to achieve something like [this](https://phub.readthedocs.io/en/latest/guides/download.html#advanced-progress-display). I'm unsure on what is the best way to implement that, so in the meantime i removed it (5307c55b64166aa8a0580fa2f24732dc9effa301). It should work like before now.
